module(name = "roo_windows_transceivers", version = "1.0.0")

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "roo_testing", version = "2.1.1", dev_dependency = True)

bazel_dep(name = "roo_display", version = "3.2.2")
bazel_dep(name = "roo_onewire", version = "2.0.10", dev_dependency = True)
bazel_dep(name = "roo_scheduler", version = "2.1.10")
bazel_dep(name = "roo_time", version = "1.4.7")
bazel_dep(name = "roo_transceivers", version = "1.1.7")
bazel_dep(name = "roo_windows", version = "1.6.1")

archive_override(
    module_name = "nanopb",
    urls = ["https://github.com/nanopb/nanopb/releases/download/nanopb-0.4.9.1/nanopb-0.4.9.1.tar.gz"],
    integrity = "sha256-iCzYRzrZMrJHh+Z2qAjk+ynBLghtILy/usxmwYMJS1w=",
    strip_prefix = "nanopb",
    patches = ["//.roo_testing/patches:nanopb_bazel9.patch"],
    patch_strip = 1,
)
