module(name = "roo_windows_transceivers", version = "1.0.0")

bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "roo_testing", version = "2.3.0", dev_dependency = True)

bazel_dep(name = "roo_display", version = "3.3.1")
bazel_dep(name = "roo_onewire", version = "2.0.13", dev_dependency = True)
bazel_dep(name = "roo_pb", version = "0.1.0")
bazel_dep(name = "roo_scheduler", version = "2.3.0")
bazel_dep(name = "roo_time", version = "2.0.1")
bazel_dep(name = "roo_transceivers", version = "1.3.0")
bazel_dep(name = "roo_windows", version = "1.7.0")
